### ISSUE TITLE
Provide a way to work with transactions

### ISSUE THREAD

**Issue by skverma618** [leafsphp/feature-requests#4]
Please provide a work around to begin transaction, commit on successful execution and rollback if any problem occurs inbetween

**Comment by mychidarko** [comment]
I'll add this to the feature requests. This will be a great addition @skverma618

**Comment by skverma618** [comment]
Indeed @mychidarko , I had to use the one provided by PDO separately. Not that it took much time but it would be great if provided by leaf itself.

**Comment by mychidarko** [comment]
Can you share your implementation?

**Comment by mychidarko** [comment]
We now have support for transactions in Leaf DB thanks to @ibnsultan. You can check out the new release and let us know if there are any problems 😂
